### ISSUE TITLE
Can't connect to an instance of Multipass on Linux 

### ISSUE THREAD

**Issue by theko2fi** [theko2fi/ansible-multipass-collection#1]
On Linux system (multipass installed via snap), the connection plugin doesn't work. Consider the `inventory.yml` file below:
```yaml
all:
  hosts:
    hale-swiftlet:
      ansible_multipass_host: hale-swiftlet
      ansible_connection: "theko2fi.multipass.multipass"
      ansible_python_interpreter: "/usr/bin/python3"
```
The command `ansible all -i inventory.yml -m ping` returns the error `[error] [sftp] cannot open local file .... Permission denied` as follows:

![image](https://github.com/theko2fi/ansible-multipass-collection/assets/72862222/ae446985-1de5-439e-8975-7c977f709db5)

## Why?

Because the temporary file (`/home/ubuntu/.ansible/tmp/ansible-local-4936rocq2lkt/tmp5c9fmlar`) created by Ansible is in a hidden folder which **snaps** can't access.

See:
- canonical/multipass#1783
- https://snapcraft.io/docs/home-interface
