### ISSUE TITLE
Parameter 'image' had no affect on selecting the image for instances

### ISSUE THREAD

**Issue by ConnonM** [theko2fi/ansible-multipass-collection#18]
I noticed when trying to use an older LTS version of Ubuntu that the image parameter has no impact.
I tried various options, 22.04, jammy etc etc.

I also noted that 'ubuntu-lts' in module_utils/multipass.py so I think the default behaviour was that it's just not passing image to the command since multipass will default to the image tagged 'lts' - which is currently 24.04. I changed this to append the image being passed but that doesn't seem to be working either, so perhaps this isn't quite working as I understand it. 

cmd = [self.cmd, "launch", "-c", str(cpu), "-d", disk, "-n", vm_name, "-m", mem, str(image)]

I tried setting valid and invalid image names and it continues without erroring. 
e.g. doesnotexist or jammy. 

Note: I upgraded Multipass to: 1.14.0 on Mac as the images for older lts releases would not refresh. 

BTW, cool project. Thank you.

**Comment by theko2fi** [comment]
Hi dear,
Thanks for using this collection and reporting probable issues.
Unfortunately, I wasn't able to reproduce this issue. I used the playbook below, and it correctly generated a VM with **Ubuntu 20.04 LTS** as the image. 
```yaml
---
- name: Prepare
  hosts: localhost
  connection: local
  tasks:
    - name: Create a Multipass VM
      theko2fi.multipass.multipass_vm:
        name: debugissue
        image: 20.04
        state: started
```
I also reviewed the `module_utils/multipass.py` code. It seems like you missed the lines below. That's where the image value is being passed to the command. 
https://github.com/theko2fi/ansible-multipass-collection/blob/436b53742611dd25e3c00a8a25feef332a080e85/plugins/module_utils/multipass.py#L131-L132 I think you might be using an outdated version of the collection. The latest one is **0.3.0**. Please execute the command below to check which version of the collection you have installed:
```bash
ansible-galaxy collection list theko2fi.multipass
```

**Note**: I tried all this with both Multipass versions 1.13.0 and 1.14.0 for Windows
