### ISSUE TITLE
Collection not working inside virtual environment

### ISSUE THREAD

**Issue by pperesbr** [theko2fi/ansible-multipass-collection#9]
Hello,

I trying to run collection inside a virtual environment, but when I run playbook I received the error: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.errors'

My config:

virtual-venv: python 3.12.1
ansible config:

```
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/home/pp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pp/multipass/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /home/pp/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/pp/multipass/.venv/bin/ansible
  python version = 3.12.1 (main, Dec 10 2023, 15:07:36) [GCC 11.4.0] (/home/pp/multipass/.venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```
My playbook:

```
---
- name: Create a Microk8s cluster with Multipass
  hosts: localhost

  tasks:
    - name: Install Multipass
      become: true
      become_user: root
      community.general.snap:
        name: multipass

    - name: Import config Multipass VMs parameters
      ansible.builtin.include_vars:
        file: nodes.yaml

    - name: Create SSH-KEY based
      community.crypto.openssh_keypair:
        path: ".ssh/id_rsa"
        type: rsa
        size: 2048
        state: present

    - name: Create Multipass VMs
      theko2fi.multipass.multipass_vm:
        name: "{{ item.name }}"
        cpus: "{{ item.cpus }}"
        memory: "{{ item.memory }}"
        disk: "{{ item.disk }}"
        state: started
      loop: "{{ nodes }}"
```

Tks,

Paulo
